/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sandw.vista;

import fev1.dif.afip.gov.ar.ArrayOfErr;
import fev1.dif.afip.gov.ar.ArrayOfFECAEDetRequest;
import fev1.dif.afip.gov.ar.ArrayOfFECAEDetResponse;
import fev1.dif.afip.gov.ar.ArrayOfObs;
import fev1.dif.afip.gov.ar.FEAuthRequest;
import fev1.dif.afip.gov.ar.FECAECabRequest;
import fev1.dif.afip.gov.ar.FECAECabResponse;
import fev1.dif.afip.gov.ar.FECAEDetRequest;
import fev1.dif.afip.gov.ar.FECAEDetResponse;
import fev1.dif.afip.gov.ar.FECAERequest;
import fev1.dif.afip.gov.ar.FECAEResponse;
import fev1.dif.afip.gov.ar.FERecuperaLastCbteResponse;
import fev1.dif.afip.gov.ar.Obs;
import static java.io.FileDescriptor.err;
import static java.lang.System.err;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.datacontract.schemas._2004._07.sge_service_contracts.Autorizacion;
import sandw.Sandwicheria;
import sandw.dominio.Agregado;
import sandw.dominio.Producto;
import sandw.dominio.Rubro;
import sandw.dominio.Venta;

/**
 *
 * @author alech
 */
public class VentanaVentas extends javax.swing.JFrame {


    /**
     * Creates new form VentanaVentas
     */
    public VentanaVentas() {
        initComponents();
        ponerRubros();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelEmpleado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelTurno = new javax.swing.JLabel();
        cboRubro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboRubros = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        opTomate = new javax.swing.JCheckBox();
        opLechuga = new javax.swing.JCheckBox();
        opMayonesa = new javax.swing.JCheckBox();
        opMostaza = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        opQueso = new javax.swing.JCheckBox();
        opHuevo = new javax.swing.JCheckBox();
        opJamon = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        botonFacturar = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Ingreso:"));

        jLabel4.setText("Nombre Empleado:");

        jLabel6.setText("Fecha y Hora de Inicio:");

        labelFecha.setText("jLabel7");

        labelEmpleado.setText("jLabel5");

        jLabel5.setText("Turno:");

        labelTurno.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelEmpleado)
                .addGap(76, 76, 76)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(labelFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(labelTurno)
                .addGap(165, 165, 165))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelEmpleado)
                    .addComponent(jLabel6)
                    .addComponent(labelFecha)
                    .addComponent(labelTurno)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel2.setText("Seleccion Rubro");

        cboRubros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboRubros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboRubrosItemStateChanged(evt);
            }
        });

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descripcion", "Precio", "Stock"
            }
        ));
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaProductosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(" Componentes "));

        opTomate.setText("Tomate");

        opLechuga.setText("Lechuga");

        opMayonesa.setText("Mayonesa");

        opMostaza.setText("Mostaza");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opTomate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opLechuga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opMayonesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opMostaza)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opTomate)
                    .addComponent(opLechuga)
                    .addComponent(opMayonesa)
                    .addComponent(opMostaza))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregados Premiun "));

        opQueso.setText("Queso");

        opHuevo.setText("Huevo");

        opJamon.setText("Jamon");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opQueso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opHuevo)
                .addGap(18, 18, 18)
                .addComponent(opJamon)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opQueso)
                    .addComponent(opHuevo)
                    .addComponent(opJamon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id de Venta", "Producto", "Precio", "Jamon", "Queso", "Huevo", "Premiums", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVentaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaVenta);
        if (tablaVenta.getColumnModel().getColumnCount() > 0) {
            tablaVenta.getColumnModel().getColumn(0).setResizable(false);
            tablaVenta.getColumnModel().getColumn(1).setResizable(false);
            tablaVenta.getColumnModel().getColumn(2).setResizable(false);
            tablaVenta.getColumnModel().getColumn(3).setResizable(false);
            tablaVenta.getColumnModel().getColumn(3).setPreferredWidth(10);
            tablaVenta.getColumnModel().getColumn(4).setResizable(false);
            tablaVenta.getColumnModel().getColumn(4).setPreferredWidth(10);
            tablaVenta.getColumnModel().getColumn(5).setResizable(false);
            tablaVenta.getColumnModel().getColumn(5).setPreferredWidth(10);
            tablaVenta.getColumnModel().getColumn(6).setResizable(false);
            tablaVenta.getColumnModel().getColumn(7).setResizable(false);
        }

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Venta");

        lblTotal.setText("0.0");

        botonFacturar.setText("Facturar");
        botonFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFacturarActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Borrar Producto");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cboRubroLayout = new javax.swing.GroupLayout(cboRubro);
        cboRubro.setLayout(cboRubroLayout);
        cboRubroLayout.setHorizontalGroup(
            cboRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cboRubroLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(cboRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cboRubroLayout.createSequentialGroup()
                        .addGroup(cboRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cboRubroLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 418, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(173, 173, 173)
                                .addComponent(lblTotal))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cboRubroLayout.createSequentialGroup()
                                .addComponent(jToggleButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonFacturar)))
                        .addGap(47, 47, 47))
                    .addGroup(cboRubroLayout.createSequentialGroup()
                        .addGroup(cboRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(cboRubroLayout.createSequentialGroup()
                                .addGroup(cboRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cboRubroLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboRubros, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(cboRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAgregar))
                                .addGap(0, 11, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        cboRubroLayout.setVerticalGroup(
            cboRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cboRubroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cboRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboRubros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cboRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cboRubroLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cboRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addGroup(cboRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1)
                    .addComponent(botonFacturar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Sistema");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Finalizar Turno");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboRubro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//         pedirLogin();
    }//GEN-LAST:event_formWindowOpened

    private void cboRubrosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboRubrosItemStateChanged
          if(cboRubros.getSelectedIndex()>-1){
              mostrarProductos();
          }
    }//GEN-LAST:event_cboRubrosItemStateChanged

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
         mostrarComponentes();
    }//GEN-LAST:event_tablaProductosMouseClicked

    private void tablaVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaVentaMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
         agregarProducto();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void botonFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFacturarActionPerformed
         facturarVenta();
    }//GEN-LAST:event_botonFacturarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        balanceTurno();
        dispose();
        pedirLogin();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tablaProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMousePressed
        mostrarComponentes();
    }//GEN-LAST:event_tablaProductosMousePressed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        quitardeLista();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonFacturar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JPanel cboRubro;
    private javax.swing.JComboBox<String> cboRubros;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelEmpleado;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelTurno;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JCheckBox opHuevo;
    private javax.swing.JCheckBox opJamon;
    private javax.swing.JCheckBox opLechuga;
    private javax.swing.JCheckBox opMayonesa;
    private javax.swing.JCheckBox opMostaza;
    private javax.swing.JCheckBox opQueso;
    private javax.swing.JCheckBox opTomate;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTable tablaVenta;
    // End of variables declaration//GEN-END:variables

    private void pedirLogin() {
        new VentanaLogin().setVisible(true);
        mostrarDatos();
    }
    
    private void ponerRubros(){
        cboRubros.removeAllItems();
        for(Rubro r:Sandwicheria.listaRubros){
            cboRubros.addItem(r.getDescripcionRubro());
        }
    }

    private void mostrarProductos() {
        Rubro r=Sandwicheria.listaRubros.get(cboRubros.getSelectedIndex());
        DefaultTableModel mat = new DefaultTableModel(new String[]{"ID","Descripcion","Precio","Stock"}, 0);
        for(Producto p:r.getListaProductos()){
            mat.addRow(new Object[]{
                p.getIdProducto(),
                p.getDescripcionProducto(),
                p.getPrecio(),
                p.getCantidad()
            });
        if ("Sandwichs".equals(r.getDescripcionRubro())){
            opHuevo.setEnabled(true);
            opJamon.setEnabled(true);
            opLechuga.setEnabled(true);
            opMayonesa.setEnabled(true);
            opMostaza.setEnabled(true);
            opQueso.setEnabled(true);
            opTomate.setEnabled(true);
            jPanel2.setEnabled(true);
            jPanel3.setEnabled(true);
        }
        else{
            opLechuga.setSelected(false);
            opMayonesa.setSelected(false);
            opMostaza.setSelected(false);
            opTomate.setSelected(false);
            opJamon.setSelected(false);
            opQueso.setSelected(false);
            opHuevo.setSelected(false);
            opHuevo.setEnabled(false);
            opJamon.setEnabled(false);
            opLechuga.setEnabled(false);
            opMayonesa.setEnabled(false);
            opMostaza.setEnabled(false);
            opQueso.setEnabled(false);
            opTomate.setEnabled(false);
            jPanel2.setEnabled(false);
            jPanel3.setEnabled(false);
        }
        }
        tablaProductos.setModel(mat);
        //mostrarComponentes();
    }
    
    private void mostrarComponentes(){
        opLechuga.setSelected(false);
        opMayonesa.setSelected(false);
        opMostaza.setSelected(false);
        opTomate.setSelected(false);
        
        opJamon.setSelected(false);
        opQueso.setSelected(false);
        opHuevo.setSelected(false);
        
        int id=Integer.parseInt(tablaProductos.getValueAt(tablaProductos.getSelectedRow(), 0).toString());
        //String seleccion = (String) tablaProductos.getValueAt(tablaProductos.getSelectedRow(), tablaProductos.getSelectedColumn());
        Producto pro = Sandwicheria.buscarProductoPorId(id);
        //for(Producto pro:Sandwicheria.getListaProductos())
        //    if(pro.getDescripcionProducto().equals(seleccion)){
            for(Agregado a:pro.getListaComponentes()){
                if("tomate".equals(a.getNombreAgregado())) opTomate.setSelected(true);
                if("lechuga".equals(a.getNombreAgregado())) opLechuga.setSelected(true);
                if("mayonesa".equals(a.getNombreAgregado())) opMayonesa.setSelected(true);
                if("mostaza".equals(a.getNombreAgregado())) opMostaza.setSelected(true);
         //   }
        }
    }
    
    public Venta venta= null;

    private void agregarProducto() {
        if(venta==null){
            venta = new Venta();
            venta.setContadorProductos(1);
        }
        if(tablaProductos.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(rootPane, "Seleccione un producto");
        }
        else {
            int id=Integer.parseInt(tablaProductos.getValueAt(tablaProductos.getSelectedRow(), 0).toString());
            Producto pro=Sandwicheria.buscarProductoPorId(id);
            if(0 != pro.getCantidad()){
                pro.setCantidad(pro.getCantidad() - 1);
                Producto nuevo=new Producto(pro);
                if(opTomate.isSelected()) nuevo.addComponente(new Agregado("Tomate", false));
                if(opLechuga.isSelected()) nuevo.addComponente(new Agregado("Lechuga", false));
                if(opMayonesa.isSelected()) nuevo.addComponente(new Agregado("Mayonesa", false));
                if(opMostaza.isSelected()) nuevo.addComponente(new Agregado("Mostaza", false));
    
                if(opJamon.isSelected()) nuevo.addPremiuns(new Agregado("Jamon", true,20));
                if(opQueso.isSelected()) nuevo.addPremiuns(new Agregado("Queso", true,30));
                if(opHuevo.isSelected()) nuevo.addPremiuns(new Agregado("Huevo", true, 20));
        
                nuevo.setIddeVenta(venta.getContadorProductos());
                venta.addProducto(nuevo);
                mostrarProductos();
                mostrarVenta(nuevo);
                venta.setContadorProductos(venta.getContadorProductos()+1);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Stock Agotado");
            }
        }
    }

    private void mostrarVenta(Producto p) {
            DefaultTableModel mat = (DefaultTableModel) tablaVenta.getModel();
            mat.addRow(new Object[]{
                venta.getContadorProductos(),
                p.getDescripcionProducto(),
                p.getPrecio(),
                p.revisarAgregado("Jamon"),
                p.revisarAgregado("Queso"),
                p.revisarAgregado("Huevo"),
                p.calcularTotalPremiuns(),
                p.getPrecio() +  p.calcularTotalPremiuns()
            });
            lblTotal.setText("$ "+venta.calcularTotal());
    }
    
    public void mostrarDatos(){
        labelEmpleado.setText(Sandwicheria.getNombreEmpleado());
        labelFecha.setText(Sandwicheria.getFechaTurno());
        labelTurno.setText(Sandwicheria.getDescripcionTurno());
    }
    
    private void facturarVenta(){
        if (venta != null){
            double total = venta.calcularTotal();
            venta.setTotal(total);
            Sandwicheria.addVentaTurno(venta);
            DefaultTableModel mat = (DefaultTableModel) tablaVenta.getModel();
            mat.setRowCount(0);
            lblTotal.setText("0.0");
            Sandwicheria.facturar(venta, this);
            venta = null;
            
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "No hay productos agregados");
        }
    }
    
    private void quitardeLista() {
        DefaultTableModel mat = (DefaultTableModel) tablaVenta.getModel();
        int idventa = (int) tablaVenta.getValueAt(tablaVenta.getSelectedRow(), 0);
        ArrayList<Producto> lista = venta.getListaProductos();
        ArrayList<Producto> lista2 = new ArrayList<>();
        for (Producto pro:lista){
            if(pro.getIddeVenta() == idventa)
                lista2.add(pro);
        }
        for (Producto pro:lista2){
            venta.removeProducto(pro);
        }
        mat.removeRow(tablaVenta.getSelectedRow());
    }
    
    private void balanceTurno() {
        JOptionPane.showMessageDialog(rootPane, "Se vendieron: \n "+Sandwicheria.cierreTurno()+"\nEl total de ingresos fue: "+Sandwicheria.calcularTotalTurno());
    }
    
}
